"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


setup(
    app=['./SeqsUI.py'],
    data_files=[],
    options={
        'py2app': {
            'iconfile': './icon/logo.ico',
            'packages': ['cffi', 'openpyxl', 'pandas', 'PyQt5']
        }
    },
    setup_requires=['py2app'],
)
